valence-rs/valence

- examples/combat.rs
- examples/conway.rs
- examples/cow_sphere.rs
- examples/raycast.rs
- examples/terrain.rs
- src/client/event.rs
This adds an (encouraged) default client event from the examples to reduce confusion for examples.
> Reduce boilerplate by making a default client event.

- src/text.rs
Adds parsing color names in the `text` module, resolves #21
> Add named text color parsing

- examples/conway.rs
This would typically go unnoticed, but upon expanding the and making meaningful use of both directions, this being an issue arises.
> Fix order of chunk creation in conway's example

- src/protocol/codec.rs
- src/protocol/packets/c2s.rs
fixes #24
I went ahead and updated `CommandExecution` too since these 2 packets are similar.
1. run `cargo r -r --example terrain`
2. run mc and join localhost
3. type any non command in chat
4. type `/help` in chat
5. see that you don't get kicked
> Update definition for ChatMessage and CommandExecution

- examples/combat.rs
- examples/conway.rs
- examples/cow_sphere.rs
- examples/raycast.rs
- examples/terrain.rs
- src/chunk.rs
- src/config.rs
- src/lib.rs
These changes will pave the way for nonblocking terrain generation in `terrain.rs`.
Need to give it another look while I'm not so tired.
> Split `Chunk` into loaded and unloaded types

- src/client.rs
- src/protocol/packets/s2c.rs
[edit]
This PR implements [ExperienceBarUpdate](https://wiki.vg/Protocol#Set_Experience) and [HealthUpdate](https://wiki.vg/Protocol#Set_Health) packets.
I decided not to introduce a new field for Total Experience, health or hunger on `Client`, storing that data and conversion between Total Experience and level with xp bar would be handled downstream.
There are two new functions on `Client`, `set_level` and `set_health_and_food`.
Their docs describe ranges of the arguments.
It is ok to send these packets on the same tick player connected, that is why I chose not to defer sending them.
Setting total_xp has no effect on the score on death screen, so I have no idea what it does. There is a todo in `set_level` docs.
* Send packet on the same tick player connected
* Outcome: packet **can** be …
> Added SetExperience and SetHealth packets

- src/client.rs
- src/config.rs
- src/server.rs
Added new methods to the Config trait, that enables implementors to use a fully custom URL.
Closes #40
> Add methods to Config to use a custom session server

- extracted/enchants.json
- extractor/src/main/java/dev/_00a/valence_extractor/Main.java
- extractor/src/main/java/dev/_00a/valence_extractor/extractors/Enchants.java
This adds basic enchantment extraction into the JSON file. Note: No rust parser has yet been written.
Do we want the top level to be an array or an object as currently defined in [enchants.json](https://github.com/valence-rs/valence/compare/main...TerminatorNL:valence:enchant-extract?expand=1#diff-bdab9517c426197356200e180fd7375d4598b135622b05cc63efbcdb62378c99)? I used the other extracted files as reference and they use objects.
> Add basic enchantment extraction

- valence_nbt/Cargo.toml
- valence_nbt/src/compound.rs
- valence_nbt/src/from_binary_slice.rs
Turns out that `BTreeMap`s are a bit faster when the element count is low.
This change also makes debugging compounds easier since the elements are displayed in sorted order.
> Replace HashMap with BTreeMap in valence_nbt

- src/client.rs
This PR implements Weather.
Closes #105
Im currently not sure how design the api for weather.
**Current State** (by Game Event)
```rust
client.set_raining(true);
client.set_rain_level(0.5); // does not depend on set_raining
client.set_thunder_level(0.3); // does depend on set_raining (or set_rain_level)
```
**Idea 2** (without set_raining)
```rust
client.set_rain_level(0.5);
client.set_thunder_level(0.3); // does depend on set_rain_level
```
**Idea 3**
```rust
client.set_rain(0.5);
client.set_thunder(0.3); // does depend on set_rain_level
client.set_thunder(0.5/*rain level*/, 0.3/*thunder level*/); // does depend on set_rain_level
```
**Idea 4**
```rust
client.set_weather(Weather::Rain);
client.set_weather(Weather::Rain, 0.5);
client.set_weather(Weather::Thunder); // depends on enabling …
```
> Implemented Weather

- examples/death.rs
- src/client.rs
- src/client/event.rs
- src/protocol/packets/s2c.rs
This PR implements dying and respawning of player and `death.rs` example.
Method for killing the client. Allows to set a message on the death screen.
To demonstrate (and to follow up on [this comment](https://github.com/valence-rs/valence/pull/34#issuecomment-1242363870)) I also created an example.
It shows how to enable death screen, kill player and respawn, including respawning in another `world`.
Once player inventory is working, interaction with compass would be added to the example.
Following tests were conducted in the `death.rs` example.
* Behavior with and without death screen enabled
* When Death screen is *enabled*, it will appear. Respawn button is clickable and works.
* When Death screen is *disabled*, respawn is immediate.
* In both instances, `ClientStatus` packet will be …
> Dying and respawning

- .gitignore
- Cargo.toml
- performance_tests/README.md
- performance_tests/players/Cargo.toml
- performance_tests/players/src/main.rs
- src/client.rs
- src/entity.rs
Adds the performance_tests/ directory.
In the future we could use our own fake client software instead of rust-mc-bot. This would make it easier to run the tests.
> Add performance tests

- src/lib.rs
- valence_nbt/Cargo.toml
- valence_nbt/src/compound.rs
- valence_nbt/src/from_binary_slice.rs
- valence_nbt/src/lib.rs
- valence_nbt/src/modified_utf8.rs
- valence_nbt/src/tests.rs
- valence_nbt/src/to_binary_writer.rs
Improves write performance and adds `encoded_len` to compounds.
> Update valence_nbt to version 0.3.0

- valence_nbt/src/value.rs
This PR only adds implementations for `From<Value>` for `Option<T>`
This allows the use of generic bounds to specify the return type and get `None` if the value does not match the type.
Example use case (absent from this PR):
```rust
fn take_assume<R>(compound: &mut Compound, key: &'static str) -> Result<R, Error>
where
Option<R>: From<Value>,
{
match compound.remove(key) {
None => Err(Error::missing_nbt_value(key)),
Some(value) => {
if let Some(value) = Option::<R>::from(value) {
Ok(value)
} else {
Err(Error::invalid_nbt(key))
}
}
}
}
```
Which would allow using the following:
```rust
let x: i32 = take_assume(&mut nbt, "xPos")?;
let y: i32 = take_assume(&mut nbt, "zPos")?;
let z: i32 = take_assume(&mut nbt, "yPos")?;
let status: String = take_assume(&mut nbt, "Status")?;
let last_update: …
```
> Add reverse From<Value> for Option<T>

- Cargo.toml
- packet_inspector/src/main.rs
- src/block.rs
- src/block_pos.rs
- src/entity/types.rs
- src/ident.rs
- src/item.rs
- src/protocol.rs
- src/protocol/byte_angle.rs
- src/protocol/codec.rs
- src/protocol/packets.rs
- src/protocol/packets/s2c.rs
- src/protocol/slot.rs
- src/protocol/var_int.rs
- src/protocol/var_long.rs
- src/text.rs
This allows packets to calculate their exact length up front. This isn't currently tested or being used for anything, but that will come in later changes.
> Add `encoded_len` method to `Encode` trait.

- examples/biomes.rs
- examples/building.rs
- examples/chest.rs
- examples/combat.rs
- examples/conway.rs
- examples/cow_sphere.rs
- examples/death.rs
- examples/entity_raycast.rs
- examples/inventory_piano.rs
- examples/parkour.rs
- examples/resource_pack.rs
- examples/terrain.rs
- performance_tests/players/src/main.rs
- src/lib.rs
This removes boilerplate code in the examples and reduces friction when getting started.
> Add prelude module to valence.

- examples/building.rs
Closes #114
Note that this is a band-aid solution to a more general problem. In the future, there should be a function in the `block` module to handle all these placement rules.
> Make replaceable blocks place correctly in the building example.

- src/protocol/packets/s2c.rs
Notchian servers [ALWAYS](https://wiki.vg/Protocol#Encryption_Request) have a `verify_token` length of 4.
This PR updates the range of the `BoundedArray` to support this.
> Set length range for `verify_token` to (4, 16)

- examples/building.rs
- src/client.rs
- src/inventory.rs
- rework `consume_one` into `consume`
- update `consume_one_held_item` to `consume_held_item` to match `consume`
- remove an unnecessary clone
Originally, I was planning on removing this function altogether. After thinking about it for a bit though, I think it provides enough of a convenience for end users to warrant keeping it.
This also implements the fix that was originally in #124
> Better `consume` for inventories

- src/protocol/byte_angle.rs
Adds `from_radians` function and `to_radians` method for `ByteAngle`.
> Implement radians conversions for ByteAngle

- Cargo.toml
- examples/biomes.rs
- examples/building.rs
- examples/chest.rs
- examples/combat.rs
- examples/conway.rs
- examples/cow_sphere.rs
- examples/death.rs
- examples/entity_raycast.rs
- examples/inventory_piano.rs
- examples/parkour.rs
- examples/resource_pack.rs
- examples/terrain.rs
- performance_tests/players/Cargo.toml
- performance_tests/players/src/main.rs
- src/biome.rs
- src/chunk/paletted_container.rs
- src/client.rs
- src/player_list.rs
- src/server.rs
- src/server/packet_controller.rs
- src/slab_versioned.rs
- valence_protocol/src/lib.rs
The `tracing` crate seems to be the go-to logging/profiling/instrumentation solution nowadays. Perhaps in the future we could use `tracing` for profiling instead of (or in addition to) the `perf`-based `cargo flamegraph` command. This would sidestep the issue of `rayon` polluting the output. I conducted an initial experiment by adding some more spans but wasn't very happy with the result.
Log messages have also been improved. There is some additional context and events are raised when clients are added/removed from the server.
> Replace `log` crate with `tracing`

- src/inventory.rs
This effectively exposes the slice `swap` method: https://doc.rust-lang.org/std/primitive.slice.html#method.swap
> add `swap_slot` to `Inventory`

- packet_inspector/README.md
- packet_inspector/src/main.rs
- src/server/packet_manager.rs
- valence_nbt/src/compound.rs
- valence_protocol/src/codec.rs
- valence_protocol/src/ident.rs
- valence_protocol/src/packets.rs
- valence_protocol/src/packets/c2s.rs
- valence_protocol/src/packets/s2c.rs
- Implement `encoded_len` for packet enums.
- Fix bug in `has_next_packet` causing a later `unwrap` to panic.
- Add robust `encoded_len` check in `PacketEncoder` for debug builds.
- Split packet inspector regex into separate "inclusive" and "exclusive" arguments because the `regex` crate does not support negative lookahead.
- Better `Debug` impls for `Ident` and `Compound`.
- Remove read/write timeouts from packet inspector.
> Update packet inspector and fix packet bugs

- crates/valence_nbt/src/from_binary_slice.rs
- crates/valence_nbt/src/tests.rs
- crates/valence_nbt/src/to_binary_writer.rs
- crates/valence_nbt/src/value.rs
In NBT, lists are allowed to have the element type TAG_End iff their length is zero. This adds an explicit `List::End` enum variant to valence_nbt.
> Support NBT lists of type TAG_End

- crates/valence_new/src/client.rs
- crates/valence_new/src/inventory.rs
- crates/valence_new/src/lib.rs
- crates/valence_new/src/server.rs
- crates/valence_protocol/src/inventory.rs
- add missing field preventing build, format
- add Inventory ECS component
- add cursor_item fields, getters, setters to Client
- add new_with_title to Inventory instead of using an Option
- add Inventory component to client entities when they connect
- add system update_player_inventories
This does not implement opening other inventories yet, planning to do that in a follow up PR.
The idea here is to have an `Inventory` component that can be used for all inventories. If you want a chest to have an inventory, give the corresponding block entity an `Inventory`. If you don't want any inventory update systems to run, simply don't give clients a player inventory.
<details>
<summary>Code used to test</summary>
```rust
use bevy_ecs::prelude::*;
use bevy_ecs::schedule::ShouldRun;
use …
```
> [ECS] Add Inventory component, re-implement player inventories

- crates/packet_inspector/Cargo.toml
- crates/packet_inspector/src/main.rs
- crates/valence/src/server/packet_manager.rs
- crates/valence_protocol/Cargo.toml
- crates/valence_protocol/src/codec.rs
Adds `tracing` to `valence_protocol` so we can log debug info about partially decoded packets. `packet_inspector` has been set to print log messages at the debug level.
> Add debug logging to valence_protocol

- crates/valence_protocol/src/text.rs
- Extends `Text`'s `Deserialize` impl to allow for deserializing JSON data types other than objects.
- Add additional `From` impls for `Text`.
- Better `Debug` impl for `Text`.
- Tweaked text unit tests.
> Non-Object Text Deserialization

- crates/valence_new/examples/inventory_test.rs
- crates/valence_new/src/client.rs
- crates/valence_new/src/inventory.rs
- crates/valence_new/src/server.rs
- add helper to convert slot ids
- implement system to handle click container events
- update inventory_test example with block platform and some chests to open
- add toggle_gamemode_on_sneak system to example
- fix query filter that was causing clients to get spammed with OpenScreen
- move state_id to `Client` component
- only send modified slots when observed inventories are changed
- force all click container packets to be handled before update packets are built and sent
- mark inventories as dirty instead of just sending the contents
- add handle_set_slot_creative to handle SetCreativeModeSlot events
- exclude clients with currently open inventories from being updated by `update_player_inventories`
1. Start the `inventory_test` example
```bash
cargo run --example inventory_test
```
2. …
> [ECS] Inventory interactions

- crates/valence_new/examples/basic.rs
- crates/valence_new/examples/inventory_test.rs
This is necessary for #198 because otherwise `cargo test -p valence_new` fails to build.
> [ECS] fix examples so cargo test doesn't fail

- crates/valence_nbt/src/lib.rs
- crates/valence_nbt/src/snbt.rs
- crates/valence_nbt/src/value.rs
To implement the hoverEvent show_item, we need an SNBT parser and a SNBT serializer.
An SNBT parser is implemented in this commit.
> Add a simple SNBT parser

- crates/valence_new/src/client/event.rs
- crates/valence_new/src/inventory.rs
- crates/valence_new/src/server.rs
Adds unit tests for all the inventory functionality that is currently implemented. It also fixes all the bugs that were found when creating these tests.
While I was working on this, I found that some of my tests were flakey because `update_client` was being scheduled before inventory systems that sent packets, resulting in packets being actually sent 1-3 updates later (depending on how things were scheduled).
```bash
cargo test -p valence_new --tests
```
> [ECS] Inventory module unit tests

- crates/valence_new/examples/conway.rs
- crates/valence_new/examples/death.rs
- crates/valence_new/examples/entity_raycast.rs
- crates/valence_new/examples/particles.rs
- crates/valence_new/examples/resource_pack.rs
- crates/valence_new/src/client.rs
- crates/valence_new/src/client/event.rs
- add client.set_resource_pack
- refactor resource pack events to unsplit them
- port resource pack example
- add set_title and set_action_bar to client
- add play_particle to client
- port particles example
- port conway example
- partially port entity_raycast example
I was unable to finish the entity_raycast example because I don't really know how the spatial index package works, but if you fix the type errors it should just work.
> [ECS] port even more examples

- .github/ISSUE_TEMPLATE/bug_report.yml
- crates/playground/build.rs
- crates/playground/src/playground.template.rs
- fixes the playground not building by default by adding a build script that makes sure the playgound is always there
- makes the playground optional in the bug report issue template
- fixes the template so it actually builds
<details>
```rust
```
</details>
Steps:
1. `cargo build -p playground`
> fix playground template, add build script

- crates/valence_new/examples/terrain.rs
- crates/valence_new/src/client.rs
- crates/valence_new/src/instance.rs
- crates/valence_new/src/instance/chunk.rs
- crates/valence_new/src/lib.rs
- crates/valence_new/src/view.rs
- Added `viewed` boolean to chunks, which is used to efficiently track chunks that can be removed from an instance because nobody is looking at it.
- Added `to_unloaded` function to loaded chunks. Used to make an unloaded clone of a loaded chunk.
- Ported terrain example to `valence_new`.
- Terrain generation is now fully asynchronous and will no longer block the main tick loop.
- Unloaded chunks closer to players are prioritized over chunks that are further away.
```bash
cargo r -p valence_new --example terrain
```
> Port terrain example

- crates/valence/src/inventory.rs
Added a quick and dirty bounds check because we haven't created drop item/itemstack event(s) yet.
use the `building` example
Steps:
1. `cargo run --example building`
2. open inventory
3. pick an item
4. drop the item outside of the inventory window
5. see that the server does not panic
fixes #233
> make dropping an item in creative not crash the server

- crates/packet_inspector/Cargo.toml
- crates/packet_inspector/src/main.rs
I've used the popular `owo-colors` library to colourise the output of the `packet_inspector`.
This makes it a lot easier to see who's sending what for debugging purposes.
In future, I'd like to be able to filter out common, low-information packets like `SetPlayerPosition` and `KeepAlive` as well, but that's not in this PR. 
No tests - just eyeball :smile:.
> Colorise the inspector output based on S2C or C2S

- crates/valence/src/client.rs
- crates/valence/src/client/event.rs
- crates/valence/src/player_list.rs
Add the ping computation system and capability to send ping to connecting clients.
Currently the player list will only update upon connection. Should another ticket be made for updating this since it seems out of scope for this issue?
Printing ping per keepalive packet on a different computer on my network. It seems to work fine but would need extra feedback.
#207
> Add ping calculation system

- crates/playground/src/extras.rs
- crates/playground/src/main.rs
- crates/valence/examples/chest.rs
- crates/valence/src/client.rs
- crates/valence/src/client/event.rs
- crates/valence/src/inventory.rs
Dropping items is heavily coupled to inventories. Clients also predict state changes when they try to drop items, so we need to be able to replicate that change in order to stay in sync.
This will also remove `DropItem` events in favor of just `DropItemStack` events. Having 2 event streams that basically mean the same thing seems verbose and error prone.
As of right now, these changes require the event loop to have a reference to the client's inventory. This seems like something we are going to need to do a lot more of to complete #199.
<details>
```rust
use tracing::info;
use valence::client::despawn_disconnected_clients;
use valence::client::event::{default_event_handler, DropItemStack};
#[allow(unused_imports)]
use …
```
> Implement Drop Item Events

- crates/valence/examples/chat.rs
Take 3 of #247.
I've added a minimal chat example - ignoring chat signing, etc. It's in the file `crates/valence/examples/chat.rs`.
Manual, unfortunately :(
Steps:
1. Open two minecraft clients, with two separate accounts (or usernames if using offline mode)
2. Connect to the server in both clients
3. Type a chat message, checking it appears to both clients, with the correct username.
4. Type a command, checking it appears only to the sender.
> Add a minimal chat example

- crates/valence_protocol/build/block.rs
- crates/valence_protocol/src/block.rs
- crates/valence_protocol/src/codec.rs
- crates/valence_protocol/src/lib.rs
- extractor/src/main/java/rs/valence/extractor/extractors/Blocks.java
- extractor/src/main/java/rs/valence/extractor/mixin/ExposeWallBlock.java
- extractor/src/main/resources/extractor.mixins.json
- extractor/src/main/resources/fabric.mod.json
This adds an API for getting the wall / attachable variant of a block. 
Unlike #117 it does not add convenience methods for orientation, and it does not modify the example to use this code.
The extractor is not tested. 
The API has some tests in the test module.
#115 - it does not fix this, as it doesn't modify the example, but it could lead to it.
> Provide API for getting the wall variant of blocks

- crates/packet_inspector/src/main.rs
- crates/valence/src/client.rs
- crates/valence/src/instance.rs
- crates/valence/src/packet.rs
- crates/valence/src/server/connection.rs
- crates/valence/src/unit_test/util.rs
- crates/valence_protocol/src/codec.rs
- crates/valence_protocol/src/lib.rs
- crates/valence_protocol/src/packet.rs
- crates/valence_protocol_macros/src/decode.rs
- crates/valence_protocol_macros/src/encode.rs
- crates/valence_protocol_macros/src/lib.rs
- crates/valence_protocol_macros/src/packet.rs
Combines the `EncodePacket` and `DecodePacket` trait into a single `Packet` trait. This makes `valence_protocol` simpler and easier to use. This can be done because all packets were made to be bidirectional in #253.
Additionally, a `packet_id` method has been added. This should help with #238.
Steps:
1. Run examples, packet_inspector, etc. Behavior should be the same.
> Replace `EncodePacket` and `DecodePacket` with `Packet`

- crates/playground/src/playground.template.rs
- crates/valence/examples/bench_players.rs
- crates/valence/examples/biomes.rs
- crates/valence/examples/block_entities.rs
- crates/valence/examples/building.rs
- crates/valence/examples/chat.rs
- crates/valence/examples/chest.rs
- crates/valence/examples/combat.rs
- crates/valence/examples/conway.rs
- crates/valence/examples/cow_sphere.rs
- crates/valence/examples/death.rs
- crates/valence/examples/gamemode_switcher.rs
- crates/valence/examples/particles.rs
- crates/valence/examples/player_list.rs
- crates/valence/examples/resource_pack.rs
- crates/valence/examples/terrain.rs
In the [examples of the `valence` crate](https://github.com/valence-rs/valence/tree/main/crates/valence/examples), the `setup()` functions are currently [exclusive systems](https://bevy-cheatbook.github.io/programming/exclusive.html). My reasoning for making these a standard system is twofold:
- Exclusive systems can be considered an advanced Bevy topic. I don't think you should be using advanced concepts in examples meant to be an introduction to the way this project/framework is used.
- In instances where developers try to use these examples, adding another startup system would result is running the systems sequentially. That leaves performance on the table (albeit only during startup).
I've chosen to _not_ include any tests besides the ones already present, because I feel that it's …
> Changed `setup()` to not be an exclusive system

- crates/valence/examples/building.rs
- crates/valence/src/inventory.rs
This mostly adds docs, but it also adds (and documents) some new helper functions:
- `set_title()` - Allows us to put `must_use` on `replace_title`
- `set_slot()` - Allows us to put `must_use` on `replace_slot`
- `set_slot_amount()` - Allows users to modify stack counts without cloning the entire stack and replacing it. Useful if the stack has a lot of NBT data.
- `first_empty_slot()`
- `first_empty_slot_in()` - Useful, trivial to provide
<details>
```rust
N/A
```
</details>
Steps:
1. `cargo test -p valence --doc`
> Inventory module docs and more helper functions

- crates/valence/Cargo.toml
- crates/valence_anvil/Cargo.toml
Sets Bevy dependencies to version 0.10 instead of the previous commit hash.
> Set bevy version to 0.10

- crates/valence_protocol/src/lib.rs
- crates/valence_protocol/src/packet.rs
- crates/valence_protocol/src/types.rs
- crates/valence_protocol_macros/src/packet.rs
Adds `packet_name` method to the `Packet` trait to help with #238.
Steps:
1. `cargo t -p valence_protocol`
> Add `packet_name`

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/pull_request_template.md
Change the issue and pull request templates.
- Remove HTML comments from the markdown because it's often not deleted and takes up space in the final commit description.
- Remove the "related" section in the PR template because links to other issues will naturally end up in the "description" section.
- Remove some placeholder text in the feature request template.
- Remove the check boxes from the bug report template to avoid creating "tasks".
- The number of sections in the bug report template was a bit daunting IMO so I trimmed it down a bit.
> Tweak templates

- crates/valence/src/server/connect.rs
- crates/valence_protocol/src/lib.rs
- crates/valence_protocol/src/packet/c2s/login/login_query_response.rs
- crates/valence_protocol/src/packet/c2s/play/custom_payload.rs
- crates/valence_protocol/src/packet/s2c/login/login_query_request.rs
- crates/valence_protocol/src/packet/s2c/play/custom_payload.rs
- crates/valence_protocol/src/packet/s2c/play/entity_tracker_update.rs
- crates/valence_protocol/src/raw.rs
Adds a `RawPacket` type to `valence_protocol`. This type simply reads and writes data to a slice, analogous to the `RawBytes` type in the same module.
Steps:
1. `cargo t -p valence_protocol`
> Add `RawPacket`

- .github/workflows/ci.yml
- crates/packet_inspector/src/main.rs
Added a caching layer to the CI
This creates a cache on first run (should exist because of this pr now)
The hash is calculated from the Cargo.toml files (recursively if i've done it correctly)
So whenever a Cargo.toml file changes, it invalidates the cache.
Local crates are _not_ cached, so they get recompiled regardless, but it already shaves off like half the total time from the action runners.
> Add caching layer to CI

- crates/valence/examples/block_entities.rs
- crates/valence/examples/building.rs
This PR replace `valence_protocol` and `valence_nbt` imports in `crates/valence/examples` with `valence` ones so you don't have to change imports or import the crates when you copy the examples and have only `valence` as a dependency.
> Replaced `valence_protocol` and `valence_nbt` imports with `valence` ones

- crates/valence/examples/parkour.rs
- crates/valence/examples/resource_pack.rs
- crates/valence/examples/text.rs
Replaced the remaining `valence_protcol` with `valence::protocol` in the examples
> Rename valence_protocol to valence::protocol

- crates/valence/src/packet.rs
With component division, the WritePacket trait was pub(crate), which disallowed writing packets outside of valence. This 1 line PR fixes that.
It might be a good idea to include examples/tests that use packet writing to catch this, but it's most likely not strictly necessary.
> tiny one line change to fix writing packets not working

- Cargo.toml
- crates/valence/src/client.rs
- crates/valence/src/client/event.rs
- crates/valence/src/component.rs
- crates/valence/src/entity.rs
- crates/valence/src/instance.rs
- crates/valence/src/inventory.rs
- crates/valence/src/lib.rs
- crates/valence/src/player_list.rs
- crates/valence/src/server.rs
- crates/valence_protocol/src/packet/s2c/play/scoreboard_display.rs
- Tweak the system schedule to be more parallel-friendly and explicit. Dependencies between systems is clearer.
- System and resource configuration is better encapsulated in each module by using plugins.
The schedule graph for `Main` now looks like this (using `bevy_mod_debugdump`):
- What to do about ambiguous systems? Many systems here are ambiguous because they take `&mut Client`, but the order they write packets isn't really important. Marking them as ambiguous explicitly with `.ambiguous_with*` across module boundaries seems difficult and cumbersome.
Steps:
1. Run examples. Check that I didn't screw up the system order.
> Refactor Schedule

- crates/valence/src/client.rs
- crates/valence/src/component.rs
Stops packets for the client's own entity being sent back to the client. This prevents the "ghost player" from appearing at spawn.
Steps:
1. `cargo r --example bench_players`
2. Press F3
3. Look at where the player spawned. Notice that there is no ghost player entity.
4. Look at received packets `rx`. Moving around in a chunk, you will not receive packets for the player's own entity. `rx` should be close to zero.
> Reimplement client self-exclusion

- crates/valence/src/client/command.rs
- crates/valence/src/client/misc.rs
- crates/valence/src/player_list.rs
Fix regressions from #317 and #315 
- Make sure player list packets get sent before player entity spawn packets are sent to prevent invisible players.
- Correctly update pose and hand swing.
Steps:
1. Load any example with two players.
2. See that players are visible.
3. See that crouching and hand swings are functioning.
> Fix player bugs

- crates/valence/src/inventory.rs
Fixed #295 by checking the slot ids of the drop event and only updating the player inventory/the target inventory accordingly.
Steps:
1. Rerun the test from #295, it works
2. Test other inventories in game
...
(No details, it only uses the chest example.)
> Fixed Panic when dropping item from inventory while chest is open #295

- crates/valence/benches/idle.rs
- crates/valence/benches/main.rs
- crates/valence/src/lib.rs
- crates/valence_core/src/lib.rs
Adds a benchmark to measure the duration of a whole server tick.
Also added `bevy_ecs` to `valence::prelude`.
Steps:
1. `cargo bench idle_update`
> Add idle tick benchmark

- crates/valence_block/Cargo.toml
- crates/valence_block/build.rs
Created a new CollisionShape struct for blocks (was previously an [f64; 6]).
Explain the steps necessary to test your changes. If you used a playground, include the code in the details below.
Steps:
1. Run the following code
<details>
```rust
use valence_block;
fn main() {
let shapes = valence_block::BlockState::STONE.collision_shapes();
println!("{:?}", shapes.collect::<Vec<_>>());
// [CollisionShape { min_x: 0.0, min_y: 0.0, min_z: 0.0, max_x: 1.0, max_y: 1.0, max_z: 1.0 }]
let shapes = valence_block::BlockState::OAK_STAIRS.collision_shapes();
println!("{:?}", shapes.collect::<Vec<_>>());
// [CollisionShape { min_x: 0.0, min_y: 0.0, min_z: 0.0, max_x: 1.0, max_y: 0.5, max_z: 1.0 }, CollisionShape { min_x: 0.0, min_y: 0.5, min_z: 0.0, max_x: 1.0, max_y: 1.0, …
```
> Use a struct to store block collision shapes

- .github/pull_request_template.md
Remove the "test plan" section from the pull request template. My justification is:
- The steps needed to test a pull request is usually obvious.
- Often the test plan is just "run `cargo test` lol"
- For small changes and tweaks, a "test plan" is overkill and amounts to frustrating busywork.
- Adds too much additional friction for new contributors.
- Large projects like Bevy are fine without it.
- Often not applicable to pull requests (like this one).
> Remove "test plan" from pull request template

- crates/valence/examples/building.rs
- crates/valence/src/tests/inventory.rs
- crates/valence_inventory/src/lib.rs
This moves the `held_item_slot` field in `ClientInventoryState` to a new component: `HeldItem`
related: pr #355
> refactor held item into a new component

- .github/workflows/ci.yml
Split fmt and clippy in ci, since fmt requires nightly, and clippy breaks on nightly
fmt only needs to run on a single platform as they _should be_ run with identical behavior across platforms
> Split fmt clippy ci

- .github/workflows/ci.yml
Describe the changes you've made. Link to any issues this PR fixes or addresses.
Version lock nightly to yesterday for fmt, it seems to fail right now, not sure why, testing if this fixes the fmt job again..
Okay, this seems to fix todays issue of nightly not wanting to install on the CI.
> Version lock nightly in CI

- crates/valence_client/src/lib.rs
- crates/valence_core/src/protocol/encode.rs
- crates/valence_instance/src/lib.rs
Added `write_packet_fallible` method to `WritePacket` trait in case the result is needed for whatever reason. Also removes some duplication by supplying a default logging message.
> Add `write_packet_fallible`

- crates/valence_client/src/lib.rs
- crates/valence_core/build/chunk_pos.rs
- crates/valence_core/build/main.rs
- crates/valence_core/src/chunk_pos.rs
- src/tests/client.rs
Change `ChunkView` so that iteration is done in sorted order by the distance to the center of the view. This is accomplished by precomputing a lookup table at compile time for all the possible view distances.
As a result of this change, the most important packets for clients to receive will typically arrive first. This is especially important when clients are loading into a new area, since the chunks closest to the client ought to be loaded first.
> Sorted Chunk View

- .github/workflows/ci.yml
- Test documentation examples with the Github CI too.
- Add a separate step for doctests in `valence-tests`.
[`--doc` seems to be mutually exclusive with all other targets](https://doc.rust-lang.org/cargo/commands/cargo-test.html#option-cargo-test---doc)
https://github.com/rust-lang/cargo/issues/6669 relevant.
> Add doctests to Github CI

- crates/valence_network/src/connect.rs
- crates/valence_network/src/lib.rs
- examples/server_list_ping.rs
- Improve the server list ping callback to make it more customizable and powerful.
- Pass all handshake data (except for `next_state` which is always `status`) to the callback instead of just protocol version.
- Allow the callback to set the version name and protocol of the response.
> Server list ping callback improvements

- Cargo.toml
- crates/valence_advancement/src/lib.rs
- crates/valence_core/src/lib.rs
- crates/valence_registry/src/tags.rs
- tools/playground/src/main.rs
Fixes #414
Updates bevy dependencies to 0.11, while removing deprecated method usage.
> Update to Bevy 0.11

- crates/valence_entity/build.rs
- Remove all of the useless clippy warnings from`valence_entity` build.rs generated file.
- `#[allow(clippy::suspicious_else_formatting)]`
> Allow clippy::suspicious_else_formatting in generated valence_entity source file

- Cargo.toml
- tools/dump_schedule/Cargo.toml
- tools/dump_schedule/README.md
- tools/dump_schedule/src/main.rs
Update the `dump_schedule` utility since `bevy_mod_debugdump` has been updated to support bevy 0.11.
- Update `bevy_mod_debugdump` to 0.8.
- Add more command line options to the tool.
> Update `dump_schedule` utility

- crates/valence_client/src/lib.rs
- crates/valence_network/src/connect.rs
Remove unnecessary username validation to support GeyserMC usernames.
Remove `is_valid_username` as discussed in #416.
> Fix username validation for GeyserMC

- crates/valence_network/src/connect.rs
- crates/valence_network/src/packet_io.rs
- Make timeouts in `valence_network` per connection rather than per packet.
- Add missing disconnect message when protocol version mismatch occurs.
- More consistent variable names.
- Remove timeouts from `PacketIo` and `try_handle_legacy_ping` call.
- Add timeout to `handle_connection` call.
- Rename `conn` -> `io`.
> Fix valence_network timeouts + other fixes

- tools/dump_schedule/README.md
- tools/dump_schedule/src/main.rs
Perform [transitive reduction](https://en.wikipedia.org/wiki/Transitive_reduction) on the output of the `dump_schedule` utility to make it easier to understand.
Send the output through the graphviz `tred` command before piping through `dot`. Can be disabled with the `--no-tred` flag.
> Add transitive reduction to `dump_schedule`

- Cargo.toml
- crates/valence_core/src/text.rs
- examples/block_entities.rs
> fix block_entities example

- crates/valence_nbt/Cargo.toml
- crates/valence_nbt/src/binary/decode.rs
- crates/valence_nbt/src/snbt.rs
- crates/valence_nbt/src/tag.rs
- crates/valence_nbt/src/value.rs
- Fix a few small things before releasing 0.5. For #428 
- Remove redundant `element_type` method from `Tag`.
- `get_tag` -> `tag`.
- Remove macro generated methods from `Value`.
- Create `From<Value> for List` impl which creates a new singleton list.
- Clean up snbt code a bit.
> Tweak `valence_nbt`

- tools/packet_inspector/README.md
Add more arguments to the docker command in the README to make it easier to use with the packet inspector.
> Add more arguments to docker command in packet inspector README

- crates/valence_inventory/src/lib.rs
- crates/valence_protocol/src/packets/play/update_selected_slot_c2s.rs
This packet wasn't right anymore because I had change it thinking it was odd that the S2c and C2s don't use the same primitive size, but it create warning so I reverse it.
Change u8 to u16 so the packet can be decode without warning.
> Fix `update_selected_slot_c2s`

- crates/valence_nbt/src/binary/decode.rs
- crates/valence_nbt/src/lib.rs
- crates/valence_nbt/src/serde.rs
- crates/valence_nbt/src/serde/de.rs
- crates/valence_nbt/src/serde/ser.rs
- crates/valence_protocol/src/impls.rs
When using valence_nbt, it's often necessary to convert to and from slices and vecs of `i8` and `u8`. But this requires unsafe code if you want to avoid copying things.
Expose the following functions in valence_nbt:
- `u8_vec_into_i8_vec(vec: Vec<u8>) -> Vec<i8>`
- `i8_vec_into_u8_vec(vec: Vec<i8>) -> Vec<u8>`
- `u8_slice_as_i8_slice(slice: &[u8]) -> &[i8]`
- `i8_slice_as_u8_slice(slice: &[i8]) -> &[u8]`
We've also made use of these functions ourselves to reduce the total amount of unsafe code. Should also help in #263
> Consolidate unsafe byte conversions in valence_nbt

- .github/workflows/ci.yml
- crates/valence_nbt/src/binary/decode.rs
- crates/valence_network/src/packet_io.rs
- crates/valence_protocol/src/packets/play/entity_damage_s2c.rs
- crates/valence_server/src/layer/chunk.rs
- crates/valence_server/src/spawn.rs
- extractor/README.md
- src/tests/boss_bar.rs
- src/tests/example.rs
- src/tests/world_border.rs
- tools/packet_inspector/src/app.rs
- tools/packet_inspector/src/lib.rs
- typos.toml
- Fix #431
- Make the CI simpler.
- Add `typos` spell checker job.
- Don't run jobs in a matrix if they don't have to.
- Update versions where possible.
- Reorder jobs.
> Simplify CI, add typos spell checker

- Cargo.toml
- crates/valence_advancement/Cargo.toml
- crates/valence_advancement/src/lib.rs
- crates/valence_boss_bar/Cargo.toml
- crates/valence_boss_bar/src/components.rs
- crates/valence_entity/Cargo.toml
- crates/valence_entity/src/hitbox.rs
- crates/valence_entity/src/lib.rs
- crates/valence_inventory/Cargo.toml
- crates/valence_inventory/src/lib.rs
- crates/valence_player_list/Cargo.toml
- crates/valence_player_list/src/lib.rs
- crates/valence_scoreboard/Cargo.toml
- crates/valence_scoreboard/src/components.rs
- crates/valence_server/Cargo.toml
- crates/valence_server/src/abilities.rs
- crates/valence_server/src/action.rs
- crates/valence_server/src/client.rs
- crates/valence_server/src/keepalive.rs
- crates/valence_server/src/op_level.rs
- crates/valence_server/src/spawn.rs
- crates/valence_server_common/Cargo.toml
- crates/valence_server_common/src/uuid.rs
- crates/valence_weather/Cargo.toml
- crates/valence_weather/src/lib.rs
- crates/valence_world_border/Cargo.toml
- crates/valence_world_border/src/lib.rs
- Add `Deref` and `DerefMut` to all components using `derive_more` crate
- Closes #444
- Add `derive_more` crate to top level `Cargo.toml` and use cargo workspace dependency in necessary crates
- Derive `DerefMut` trait to components that provide mutable access to underlying data
- Derive `Deref` trait to components that provide immutable access to underlying data
I made some compilation time benchmarks on my machine (i don't know good way to do compile time benchmarks so i ran debug mode compilation couple of times before and after the change)
Clean `Valence` compilation
- Before: 2m 2s
- After: 2m 5s
Clean default `playground` example
- Before: 11s
- After: 11s
> Add Deref and DerefMut to all components (where appropriate)

- crates/valence_nbt/src/lib.rs
- crates/valence_nbt/src/list.rs
- crates/valence_nbt/src/value.rs
- `valence_nbt::List` is kind of inconvenient to work with when you are not expecting a specific type of list. You often have to match over every type of list.
Just one example, I would like to write this code:
```rs
fn do_something_with_nbt_value(value: valence_nbt::Value) { ... }
for item in list {
do_something_with_nbt_value(item);
}
```
- Added several convenience methods to `valence_nbt::List` to hopefully reduce the `match` boilerplate in client code, including iterator methods.
- I had to introduce borrowing `ValueRef` and `ValueRefMut` types. These are only used for list access and modification. I cannot use `&Value` because the list does not store that type so there is nothing to reference, and worse, `&mut Value` would allow for non-heterogeneous lists.
> `valence_nbt::List` convenience methods

- crates/valence_nbt/src/list.rs
- It was annoying to remove elements from a `valence_nbt::List` by a predicate.
- Add `valence_nbt::List::retain`, which the same API as `Vec::retain_mut` (similar to `HashMap::retain`, `Vec::retain_mut` only exists because they forgot to pass a mutable reference to `Vec::retain` and changing it would be breaking).
> Add valence_nbt::List::retain

- tools/packet_inspector/Cargo.toml
- tools/packet_inspector/build.rs
- tools/packet_inspector/src/app.rs
- tools/packet_inspector/src/lib.rs
- tools/packet_inspector/src/main_cli.rs
- tools/packet_inspector/src/packet_io.rs
- tools/packet_inspector/src/packet_registry.rs
- The packet inspector didn't respond properly when the server had encryption enabled
- Fixes #404 
- The proxy now listens for authentication packets (LoginHelloS2c), kicking the player out with an appropriate message and shutting down the connection when that happens.
- The proxy code was also refactored a fair bit to allow easier two-way communication between the proxy tasks and the UI code, although so far it's mostly unused (I only wrote code for the CLI to print online mode errors whenever the server requests online mode, the GUI hasn't changed, although I may come back and add more info there in the future).
Also, for the sake of completeness, here's how the error looks like in-game:
> Add online mode detection in the Packet Inspector

- crates/valence_protocol/src/bounded.rs
Be able to directly display `Bounded` struct without getting the inner value.
Display the inner value if it impl `Display` itself.
> Impl display for `Bounded`

- Cargo.toml
- crates/valence_anvil/Cargo.toml
- crates/valence_anvil/src/lib.rs
- Follow on from #510 by adding the ability to write and delete chunks in anvil files.
- Add a `write` feature to `valence_anvil`, behind which the region file allocator is hidden (this is a bit more work to keep track of).
- Users can change the compression method and whether to write oversized chunks, in case they want to write anvil files compatible with older versions of Minecraft.
- `LruCache::try_get_or_insert_mut` is something I have [pull requested](https://github.com/jeromefroe/lru-rs/pull/178) to `lru`, we can switch to that once it's merged.
> Add ability to write anvil chunks

- .github/workflows/ci.yml
The warnings weren't causing the CI step to fail as desired.
> Make `cargo doc` fail on warnings in CI

- .github/workflows/ci.yml
- crates/valence_text/Cargo.toml
Unused dependencies can be left in `Cargo.toml` by accident.
- Add `cargo-udeps` to CI.
> Add `cargo-udeps` to CI

- crates/valence_anvil/src/lib.rs
- crates/valence_nbt/src/binary.rs
- crates/valence_nbt/src/binary/decode.rs
- crates/valence_nbt/src/binary/encode.rs
- crates/valence_nbt/src/binary/tests.rs
- crates/valence_nbt/src/conv.rs
- crates/valence_nbt/src/lib.rs
- crates/valence_nbt/src/serde/de.rs
- crates/valence_nbt/src/serde/ser.rs
- crates/valence_nbt/src/tag.rs
- crates/valence_protocol/src/impls/other.rs
- crates/valence_registry/src/codec.rs
`valence_nbt` could use some adjustments.
- Move top-level conversion functions to `conv` module.
- Remove public `Display` impl from `Tag`.
- Remove implicit "null" byte check when decoding compounds. This check can be done in advance if desired.
- Remove potentially dangerous memory preallocation when decoding binary.
- Make `Compound::to_binary` and `Compound::from_binary` free functions for discoverability and familiarity with serde_json.
> NBT Tweaks

- crates/valence_inventory/src/lib.rs
This PR adds functionality to allow the server to change the users selected hotbar slot using `HeldItem::set_slot(36..44)`
> Add HeldItem::set_slot

- crates/valence_server/src/client.rs
- examples/custom_npc.rs
- bare minimum to do custom skins on player entities
- add a `CustomSkin` component
This PR aims to make it a little bit easier to create player entities with custom skins. This is common for things like NPCs.
closes #460
- Added a new example.
- Ideally, we could provide the `CustomSkin` component inside valence itself, maybe in a new `valence_util` crate?
> Custom skin example

- examples/building.rs
In the building example, respect the `face` of the interaction event to allow placing the block in the proper direction.
> respect placement orientation of block

- crates/valence_inventory/src/validate.rs
Hi,
I was playing around with the chest example.
After adding an item with NBT data, I noticed I was unable to remove it from the chest.
Sourced the error down to this check. All I have done is not check the NBT data for now.
Same as in last comment of #292 .
Only item kind and count checked, nbt ignored.
Kind Regards,
Mac
> Solve inability for items with improper NBT data to be moved out of inventories

- crates/valence_anvil/README.md
- crates/valence_ident/README.md
- crates/valence_nbt/README.md
- crates/valence_network/src/lib.rs
- crates/valence_text/README.md
- crates/valence_text/src/lib.rs
- crates/valence_world_border/README.md
- crates/valence_world_border/src/lib.rs
- Replace references to the old Fandom wiki with the new wiki. See [here](https://minecraft.wiki/w/Minecraft_Wiki:Moving_from_Fandom) for details
- Replace references to the old Fandom wiki with the new wiki
> Replace fandom references with new wiki

- crates/valence_entity/build.rs
When encoding `ItemStack`s in `TrackedData` the `ItemStack` itself is not optional as it was previously implemented. For further context, when encoding an `ItemStack` it will only encode as one byte if the `ItemStack` is empty.
- Fixes #537 
- Remove the optional wrapping around the `ItemStack` value when encoding it in the `TrackedData`.
> Fix encoding `ItemStack` in `TrackedData`

- crates/valence_entity/src/lib.rs
Fix encoding villager level in `TrackedData`. The level should be encoded as a `VarInt` when it was being encoded as an `i32`.
- Fixes #453 
- The level should be encoded as a `VarInt` when it was being encoded as an `i32`.
> Fix encoding villager level in `TrackedData`

- crates/valence_server/src/client.rs
There was a bug in the implementation of `DisconnectClient` where the client would be disconnected before receiving the kick message.
Replace `entity.remove::<Client>();` with `entity.insert(Despawned);`. This way, the client will be removed at the end of the tick to give time for the packets to be sent.
> Note: Removing that line altogether also works with a vanilla client, however, it is trivial for a custom client to ignore the packet, and thus having an "anti-kick" exploit.
```rs
use valence::client::{despawn_disconnected_clients, DisconnectClient};
use valence::log::LogPlugin;
use valence::network::ConnectionMode;
#[allow(unused_imports)]
use crate::extras::*;
const SPAWN_Y: i32 = 64;
pub fn build_app(app: &mut App) {
app.insert_resource(NetworkSettings { …
```
> Fix `DisconnectClient` disconnecting clients before kicking them with message

- crates/java_string/src/slice.rs
- crates/valence_anvil/src/lib.rs
- crates/valence_nbt/Cargo.toml
- crates/valence_nbt/src/binary.rs
- crates/valence_nbt/src/binary/decode.rs
- crates/valence_nbt/src/binary/encode.rs
- crates/valence_nbt/src/binary/modified_utf8.rs
- crates/valence_nbt/src/binary/tests.rs
- crates/valence_nbt/src/compound.rs
- crates/valence_nbt/src/lib.rs
- crates/valence_nbt/src/list.rs
- crates/valence_nbt/src/serde/de.rs
- crates/valence_nbt/src/serde/ser.rs
- crates/valence_nbt/src/value.rs
- crates/valence_protocol/src/impls/other.rs
- Generify `valence_nbt` to allow other types of `String`, such as `JavaString`.
- A side effect of this is that NBT using `Cow<str>` is now also possible.
- `valence_nbt::Compound`, `valence_nbt::List` and `valence_nbt::Value` all now have a generic `S` parameter for the string type, which defaults to `String`.
- Extra `From` implementations for `Cow` strings have been added.
- Support for `JavaString` in `valence_nbt` has been added behind the `java_string` feature flag.
- Added an `AsBorrowed` trait to query a compound, to allow `Compound<JavaString>` to be queried by `&str`.
- Added `FromModifiedUtf8` and `ToModifiedUtf8` traits to support decoding and encoding custom strings, respectively.
- `valence_anvil` has been adapted to allow custom string types in compounds in anvil files.
- …
> Generify `valence_nbt` to allow other types of String

- crates/java_string/src/char.rs
- crates/java_string/src/owned.rs
- crates/java_string/src/slice.rs
- crates/valence_nbt/src/list.rs
- crates/valence_nbt/src/snbt.rs
- crates/valence_nbt/src/value.rs
- crates/valence_network/src/lib.rs
- crates/valence_server/src/layer/chunk/loaded.rs
- Follow up on https://github.com/valence-rs/valence/pull/546#discussion_r1349688466
- Use monospace links where applicable.
- I also found a reference to the old wiki which I replaced with the new one.
> Use monospaced links where applicable

- crates/java_string/src/slice.rs
- Add missing `AsRef` impl for `JavaStr`.
- `str` has the same thing.
> Add missing AsRef impl

- .github/workflows/website.yml
- Make "setup Rust toolchain" step consistent with ci.yml.
- Stop website.yml from failing due to outdated Rust toolchain (caching issue?)
- Use `actions-rust-lang/setup-rust-toolchain@v1.5.0`
> Simplify website.yml

- crates/valence_entity/build.rs
See #557
Will be necessary to implement #556 and #558
Implement absorption for ALL living entities.
Make a special case for LivingEntity for Absorption since it's untracked.
<details>
```rs
use valence::client::despawn_disconnected_clients;
use valence::entity::living::Absorption;
use valence::log::LogPlugin;
use valence::network::ConnectionMode;
#[allow(unused_imports)]
use crate::extras::*;
const SPAWN_Y: i32 = 64;
pub fn build_app(app: &mut App) {
app.insert_resource(NetworkSettings {
connection_mode: ConnectionMode::Offline,
..Default::default()
})
.add_plugins(DefaultPlugins.build().disable::<LogPlugin>())
.add_systems(Startup, setup)
.add_systems(EventLoopUpdate, toggle_absorption_on_sneak)
.add_systems(Update, (init_clients, …
```
> Absorption

- tools/packet_inspector/src/app/filter.rs
- tools/packet_inspector/src/app/hex_viewer.rs
- tools/packet_inspector/src/app/packet_list.rs
The Hex Viewer would write the raw data in white, on white background, when in light mode. This fixes that.
The Color of the text is now not hardcoded anymore, but inferred.
> Fixed Hex Viewer writing white text on white background when in light mode

- crates/valence_entity/build.rs
- crates/valence_server/src/client.rs
- src/tests.rs
- src/tests/hunger.rs
- Food and saturation currently don't exist for the player in valence
- Closes #565 
Adds food and saturation to the `PlayerEntity` and tells the client about any changes. The only problem right now is that the default value for `Health` is the same for ALL entities, so the server tells the client that their health is at 14 when it should be at 20.
Uncertain if best approach. Please lmk if another approach would be better
> Added food and saturation

- Cargo.toml
- crates/valence_entity/src/active_status_effects.rs
- crates/valence_entity/src/attributes.rs
- crates/valence_nbt/src/compound.rs
IndexMap remove methods are deprecated in favor of [swap|shift]_remove
match serde_json's implementation of swap and shift remove
> fix indexmap deprication warnings

- Cargo.toml
- crates/java_string/README.md
- crates/java_string/src/char.rs
- tools/dump_schedule/README.md
- tools/packet_inspector/src/app.rs
- tools/packet_inspector/src/app/packet_list.rs
- tools/packet_inspector/src/main.rs
- tools/packet_inspector/src/tri_checkbox.rs
- tools/playground/src/playground.template.rs
As discussed in the discord I will defer updating bevy to its own PR. (1/2) of point num 3 of #620 . I am not sure how to close all the dependabot PRs.
> update deps (excluding bevy)

- crates/valence_command/src/graph.rs
- crates/valence_command/src/manager.rs
- The already visited map was using edge-type not the id of the parent and the node its pointing too this leads to a situation where if two nodes redirect to the same node only one path will be sent to the client while the other is ignored (this could even be non deterministic)
- The macro supports structs and enums now updated docs to reflect
- Added space in docs for readability
- added some debug and trace logging for commands (Is it a good idea to have the command dispatched message on info?)
> Fix command tree & small improvements

- flake.lock
- flake.nix
- shell.nix
This PR adds a Nix development environment that will allow Nix users to easily build and work on valence without having to write their own. 
If using flakes you can get into the development shell using `nix develop`, otherwise you can use `nix-shell`
> Add Nix development environment for the Nix users out there

- flake.nix
- Added support for aarch64 platform for NixOS
- Just add the `aarch64-linux` field in `flake.nix`
> nix: add aarch64 support

- crates/valence_server/src/action.rs
For some silly reason when I updated to bevy 0.14 I copy pasted some code and forgot to change it. This fixes that.
> fix digging stopping on start

- website/book/1-getting-started/setup.md
Fix the incorrect code in the guidebook setup chapter.
Change `visible_entity_layers.insert(layer);` to `visible_entity_layers.0.insert(layer);`
> Fix bug in guidebook code

- README.md
By a vote on the discord server 17 to 0 to remove this note. This is due to lack of interest in this rewrite and lack of control over Evenio and the tracking issue itself.
> remove rewrite note

- flake.lock
I noticed that when trying to diagnose an issue that we don't compile with the current nix lock, (rust being to old) 
```
error: package `tokio-macros v2.4.0` cannot be built because it requires rustc 1.70 or newer, while the currently active rustc version is 1.65.0-nightly
```
ran `nix flake update`, and now it brings in a recent enough rust nightly for everything to compile
> update nix flake environment

- crates/valence_inventory/src/lib.rs
- src/tests/inventory.rs
Attempts to solve the issue shown in discord https://discord.com/channels/998132822239870997/1292890441011957830
where doing  has no effect in a "open inventory"
Looks like an oversight in the system to update the open inventories, no attempt to send any packet to the user was made when the `CursorItem` component was updated by any system
Playground to reproduce the issue solved by this pr.
```rust
use valence::interact_block::InteractBlockEvent;
use valence::inventory::ClickSlotEvent;
use valence::log::LogPlugin;
#[allow(unused_imports)]
use crate::extras::*;
const SPAWN_Y: i32 = 64;
const CHEST_POS: [i32; 3] = [0, SPAWN_Y + 1, 3];
pub(crate) fn build_app(app: &mut App) {
app.insert_resource(NetworkSettings {
connection_mode: ConnectionMode::Offline, …
```
> fix so cursor packet is sent to client with open inventories

- crates/valence_inventory/src/lib.rs
- src/tests/inventory.rs
- ability to make inventories read only (player should be able to click things in the inventory and still emit a click event, this can be useful for creating inventory menus. 
- closes  #427
- related #307 #355 
- adds a public ``readonly: bool`` field to the ``Inventory`` component, that will make any interactions with this item impossible (includes: moving, shift moving, hotbar moving, dropping) if a player inventory is readonly, then the player will also not be able to drop items (even when not in the inventory), so the drop event will not be emitted (this could be changed if requested)
- when implementing this i discovered a bug where a player is not able to put a item from a open inventory in the offhand (by hitting F) that will cause a desync. On the client the item will be in the …
> Readonly inventory

- flake.nix
When trying to use the packet inspector I noticed that it could not be ran on nix, the `nix develop` simply does not include the required libraries.
I added dependencies listed for bevy window applications to work: https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md#nix and cleaned up the flake a bit while I was at it.
> update flake to support the egui packet inspector

- crates/valence_inventory/src/lib.rs
This pr attempts to solve some components that got triggered unnecessarily  
can be observed with a simple system like this:
```rust
fn log_inventories(invs: Query<(Entity, &Inventory), Changed<Inventory>>) {
for inv in invs.iter() {
println!("inventory updated");
}
}
```
the above system will print each tick when an inventory is open, this will result in systems like the one above will trigger unnecessarily 
To solve this I found the places where we currently "reset" some state in the inventory module each tick and replaced the modifications with alternatives that only trigger a modification if the value needed to be reset (was not in the reset state)
> Fixes instances in inventory module where unnecessery updates happened

- crates/valence_inventory/src/lib.rs
- crates/valence_inventory/src/validate.rs
- src/tests/inventory.rs
Fixes some re-syncs because the validation did not accept the now specific cases (all of the affected modifications where cases where the user did not modify the inventory)
Cases like:
- user clicks without an item on the cursor outside the inventory
- user clicks on the margin area without an item held
- user clicks on an empty slot when not holding anything 
- user uses hotbar keybinds on an empty slot to an empty hotbar slot
This causes unneccery re-syncs to the client and also unneccery logs indicating some illegal client packets, while these packets are totaly fine
adjusted packet validation logic to allow these cases, but also check for "conservation of mass" when these special magic slot ids shows up
modified the handling code to basically ignore these changes, (I guess there is …
> handle clicks outside inventory and non modifying clicks

- examples/item_menu.rs
Adds a example for using an inventory with the ``readonly`` flag as a item menu (using a ``ItemMenu`` component, that can be attached to a player)
related #307
video clip:
https://github.com/user-attachments/assets/441e165a-139a-43ec-9970-3055c7f7f79a
> add ``item_menu`` example

- crates/valence_inventory/src/validate.rs
Client NBT can be different from whats on the server (e.g when you have armor on you and you move it, the client will add the Damage value). For ``ClickMode::ShiftClicking``/``ClickMode::Click`` this is already handled https://github.com/valence-rs/valence/blob/76fb18f185913a9279862a3084787b2afeb514f2/crates/valence_inventory/src/validate.rs#L198.
Now its also handled for `ClickMode::Hotbar`
> ignore client nbt for hotbar click

- crates/valence_inventory/src/lib.rs
- src/tests/inventory.rs
- fixes #666
- also check for changes in the player's `Inventory` when viewing an open inventory
> Fix desync when modifying player inventory (from valence) when player is viewing an open inventory 

- crates/valence_inventory/src/lib.rs
fixes a desync where a player with readonly inventory perfoms a block interaction (such as placing a block).
> resync readonly inventory after block interaction

- crates/valence_command_macros/src/lib.rs
Fix empty scopes in command macros and make scopes effect alternate enum paths.
> Fix empty scopes in command macros and make scopes affect alternate enum paths

- crates/valence_equipment/src/interaction_broadcast.rs
- crates/valence_equipment/src/lib.rs
- examples/equipment.rs
To broadcast players' item interactions to other players as part of `EquipmentPlugin`
When a player has the `EquipmentInteractionBroadcast` component:
- Set the "use_item" LivingFlag to true whenever an `InteractItemEvent` is received
- Set the flag false when a `PlayerActionC2s` packet with a `PlayerAction::ReleaseUseItem` action is received
> Broadcast equipment interaction

- crates/java_string/src/slice.rs
- crates/valence_network/src/lib.rs
- tools/stresser/Cargo.toml
Make the stresser compile properly again.
Current you get this error when you attempt to compile:
```
error[E0599]: no method named `set_compression` found for struct `PacketDecoder` in the current scope
--> tools/stresser/src/stresser.rs:89:25
|
89 |                     dec.set_compression(CompressionThreshold(threshold));
|                         ^^^^^^^^^^^^^^^ method not found in `PacketDecoder`
error[E0599]: no method named `set_compression` found for struct `PacketEncoder` in the current scope
--> tools/stresser/src/stresser.rs:90:25
|
90 |                     enc.set_compression(CompressionThreshold(threshold));
|                         ^^^^^^^^^^^^^^^ method not found in `PacketEncoder`
```
Enable the `compression` feature in `valence_protocol` in the stresser `Cargo.toml` file.
> Fix stresser compilation issue

- .github/workflows/website.yml
Fix the build error in the Publish Website workflow.
The error message:
`Missing download info for actions/upload-artifact@v3`
Update the `upload-pages-artifact` version from `v2` to `v3`
> Fix Publish Website Workflow

- .github/workflows/ci.yml
Specify the Rust toolchain version in the CI workflows so that unrelated issues don't pop up in PRs.
Replace all instances of `toolchain: "nightly"` with `toolchain: "1.89.0"`
> Pin Rust version in CI
