examples/conway.rs, src/client.rs, src/client/event.rs
Adds a client event for when a player interacts with (right clicks) a block
=> Add ClientEvent::InteractWithBlock

examples/conway.rs, src/client.rs, src/protocol/packets/s2c.rs
This adds an action bar packet + function, as well as integration into conway.
=> Add action bar support

Cargo.toml
Changed the `Cargo.toml` to allow full optimization of dependencies and minimally optimize the binary to allow proper testing without timeouts and errors due to overload.
=> Activate optimitations in dev profile

.github/workflows/rust.yml, src/client.rs, src/entity.rs, src/ident.rs, src/protocol/slot.rs
Testing to see what the actions do.
=> Add clippy lints and format checks

Cargo.toml, examples/combat.rs, examples/conway.rs, examples/cow_sphere.rs, examples/raycast.rs, examples/terrain.rs, src/config.rs, src/server.rs
Verify that it works by hovering your mouse over the player count in the cow_sphere example.
=> Implement the player sample

src/client.rs, src/protocol.rs, src/protocol/packets.rs, src/protocol/packets/c2s.rs, src/protocol/packets/s2c.rs
Adds the inventory packets so we can use them with `packet_inspector`.
=> Add inventory packets

packet_inspector/Cargo.toml, packet_inspector/README.md, packet_inspector/src/main.rs, src/protocol/codec.rs, src/protocol/packets.rs
Adds a regex argument to the packet_inspector allowing it to be somewhat useful for once.
See the updated README for instructions.
=> Packet filtering

examples/inventory_piano.rs, src/client.rs, src/client/event.rs, src/lib.rs, src/protocol.rs, src/protocol/packets.rs, src/protocol/packets/c2s.rs, src/slot.rs
This implements some of the client events related to inventories. I'm sure there's more, but this PR was starting to get a bit large. `DropItem` can be improved to include the item that is being dropped once we are keeping track of inventories.
related: #53
1. Run the new `inventory_piano` example
```bash
cargo r --example inventory_piano
```
2. Open your inventory
3. Start clicking on slots the hotbar.
4. You should hear piano notes being played.
5. Click on the right most hotbar slot to change to survival.
6. Start clicking on slots the hotbar again.
7. You should still hear piano notes being played.
1. Run the following example:
<details>
```rust
use std::net::SocketAddr;
use std::sync::atomic::{AtomicUsize, Ordering};
use log::LevelFilter;
use num::Integer;
use valence::biome::Biome; …
```
=> inventory client events

src/config.rs
Server was only reachable over localhost (127.0.0.1)
Fixes #77
=> Listen on any network interfaces #77

src/client.rs
Add function to set client time
Fixes #55
=> Set time of day #55

extractor/README.md
=> add readme for extractor

src/config.rs, src/server.rs
This adds the `prevent-proxy-connections` server property and implements it into valence.
Note that if the server is in offline mode, this changes nothing.
By default, proxy connections are allowed.
Fixes https://github.com/valence-rs/valence/issues/95
=> Implement prevent-proxy-connections

.github/workflows/ci.yml, Cargo.toml, valence_nbt/Cargo.toml, valence_nbt/README.md, valence_nbt/src/compound.rs, valence_nbt/src/error.rs, valence_nbt/src/from_binary_slice.rs, valence_nbt/src/lib.rs, valence_nbt/src/tag.rs, valence_nbt/src/tests.rs, valence_nbt/src/to_binary_writer.rs, valence_nbt/src/value.rs
This also adds another check in CI
=> Move valence_nbt to main Valence repo.

build/enchant.rs, build/main.rs, src/enchant.rs, src/lib.rs
This is a continuation of #93. But now we can expose the enchants in Rust.
Please have a look if this is the format you'd like to see, I am willing to change everything :+1:
Currently, all enchantments have a level field, but I included a docstring that informs developers about the vanilla-compatible levels.
If this PR is approved, we can implement functionality of enchants in [src/enchant.rs](https://github.com/valence-rs/valence/compare/main...TerminatorNL:enchantment-parser-rust?expand=1#diff-26da930a8457af3c2a733bb3502f558e1c8568120b9e4d175a384d6771692163). I left it blank for now because I am not sure if it's within the scope of Valence.
The following file is generated:
<details>
<summary>/out/enchant.rs (Click to see contents)</summary>
```rust
#[derive(Debug, Clone, PartialEq, Eq, …
```
=> Expose enchantments to Rust

src/client.rs, src/player_list.rs
=> Skip spawn of non visible player characters

src/client.rs, src/protocol/slot.rs
As discussed in #75. Making this as a seperate PR to get ahead of potential merge conflicts.
=> change `Slot` enum into alias of `Option<ItemStack>`

src/biome.rs, src/client.rs, src/dimension.rs, src/ident.rs, src/protocol.rs, src/protocol/packets/c2s.rs, src/protocol/packets/s2c.rs, src/text.rs
This lifetime will be useful for zero-copy decoding later.
=> Clean up ident module and add lifetime

src/item.rs, src/protocol/slot.rs
As discussed in #75. Making this as a seperate PR to avoid merge conflicts later.
=> clamp `ItemStack` item count to range 1-127

examples/biomes.rs, examples/building.rs, examples/conway.rs, src/chunk.rs, src/chunk/paletted_container.rs, src/client.rs, src/config.rs, src/server.rs
=> Correctly encode biomes

build/block.rs, extractor/src/main/java/rs/valence/extractor/extractors/Blocks.java, src/client.rs
=> Add replaceable boolean to block states

examples/chest.rs, src/client.rs
- run `chest` example
- try to open the chest
=> add `open_inventory` to clients

src/client.rs
The `block_change_sequence` wasn't getting updated when placing blocks only when breaking blocks, this results in ghost block states on the client. Ghost block states is when you place a block e.g a torch, and then when you break a block, the torch changes block state, e.g loses it's facing. This also means that blocks are not being placed right, but I hope to fix this with #117.
I also added `cmp::max(...)`, because if a modded client sent a malicious packet, where the sequence is shorter then the previous they sent, thay could mabye revert block placement/breaking they previously had done?
=> Block sequence isn't getting synced when placing blocks

src/player_textures.rs
Combines `PlayerTextures` and `SignedPlayerTextures` into one type. The skin URL is now non-optional because it appears to always be present.
=> Redesign `SignedPlayerTextures`

src/client/event.rs
fixes #133
1. run building example
2. open inventory
3. place any item in hotbar
4. try to pick it up
5. see that it does not disappear
=> don't bother marking the inventory as dirty when handling SetCreativeModeSlot

src/client.rs, src/config.rs, src/ident.rs, src/lib.rs, src/protocol/packets.rs, src/protocol/packets/c2s.rs, src/protocol/packets/s2c.rs, src/server.rs, src/server/login.rs, src/username.rs, src/util.rs
This is analogous to the existing `Ident<S>` type.
=> Add `Username<S>` type

examples/inventory_piano.rs
```
cargo r -r --example inventory_piano
```
=> re-implement inventory_piano example

valence_protocol/Cargo.toml, valence_protocol/benches/benches.rs, valence_protocol/src/codec.rs
Adds criterion benchmarks for some packets and `VarInt` in `valence_protocol`
=> Valence protocol benchmarks

crates/valence/build/main.rs, crates/valence/src/client.rs, crates/valence_derive/src/decode.rs, crates/valence_derive/src/encode.rs, crates/valence_protocol/build/block.rs, crates/valence_protocol/build/main.rs, crates/valence_protocol/src/block.rs, crates/valence_protocol/src/impls.rs, crates/valence_protocol/src/lib.rs, crates/valence_protocol/src/packets/s2c.rs, crates/valence_protocol/src/recipe.rs, crates/valence_protocol/src/types.rs
Also improve generated `Encode`, `Decode` error messages and fix unnecessary build script reruns.
=> Add recipe and tags packets

crates/valence_nbt/src/from_binary_slice.rs, crates/valence_protocol/Cargo.toml, crates/valence_protocol/src/packets/c2s.rs, crates/valence_protocol/src/packets/s2c.rs, crates/valence_protocol/src/packets/s2c/player_chat_message.rs, crates/valence_protocol/src/packets/s2c/player_info_update.rs, crates/valence_protocol/src/packets/s2c/set_equipment.rs, crates/valence_protocol/src/packets/s2c/update_advancements.rs, crates/valence_protocol/src/text.rs, crates/valence_protocol/src/types.rs
=> Implement remaining clientbound packets

crates/valence_new/examples/building.rs, crates/valence_new/examples/chest.rs, crates/valence_new/examples/inventory_piano.rs, crates/valence_new/examples/text.rs, crates/valence_new/src/client.rs, crates/valence_new/src/inventory.rs, crates/valence_new/src/server.rs
- set up some examples to port over
- finish chest example
- finish implementing inventory piano, except the sound effects don't work (which is kinda the entire point :/)
- finish implementing text example
- impl held item event handling
- finish building example
=> [ECS] port building, chest, inventory_piano, text examples

crates/valence_new/examples/biomes.rs, crates/valence_new/examples/death.rs, crates/valence_new/examples/parkour.rs, crates/valence_new/src/client.rs
- add kill() and win_game() to client
- add death example (not a port in the interest of making the example as minimal as possible)
- port biomes example
- add kick method to client
- port parkour example
=> [ECS] port more examples

crates/valence_new/examples/gamemode_switcher.rs
Very crude command interpreter to make game mode switching work via F3 + F4 if client's OP level is high enough.
=> [ECS] Game mode switching (F3+F4)

.github/workflows/ci.yml, CONTRIBUTING.md
- fix playground causing CI to choke
- fix typo
<details>
```rust
```
</details>
Steps:
1.
=> fix playground ci

crates/valence/src/client.rs, crates/valence/src/dimension.rs, crates/valence/src/entity.rs, crates/valence/src/instance.rs, crates/valence/src/player_list.rs
- add docs to `player_list` module
- add docs for `instance` module
- update docs in `client` module
- fix reference in dimension docs
- update `entity` module docs a little
<details>
```rust
```
</details>
Steps:
1. `cargo test -p valence --doc`
=> [ECS] update docs for `player_list`, `instance`, `client`, `entity`

crates/valence/src/biome.rs, crates/valence/src/client.rs, crates/valence/src/config.rs, crates/valence/src/dimension.rs, crates/valence/src/lib.rs, crates/valence/src/server.rs
- fix broken links in docs
- add minimal top level docs
<details>
```rust
```
</details>
Steps:
1. `cargo doc -p valence`
=> [ECS] make `cargo doc` pass for `valence`

crates/valence_protocol/src/lib.rs
<details>
```rust
```
</details>
Steps:
1.
=> adjusts the derive tests so they build again

crates/valence/src/instance/chunk.rs
Clean up unresolved issues from #32
=> Block entity fixes

crates/playground/src/playground.template.rs, crates/valence/Cargo.toml, crates/valence/examples/bench_players.rs, crates/valence/examples/biomes.rs, crates/valence/examples/block_entities.rs, crates/valence/examples/building.rs, crates/valence/examples/chat.rs, crates/valence/examples/chest.rs, crates/valence/examples/combat.rs, crates/valence/examples/conway.rs, crates/valence/examples/cow_sphere.rs, crates/valence/examples/death.rs, crates/valence/examples/gamemode_switcher.rs, crates/valence/examples/parkour.rs, crates/valence/examples/particles.rs, crates/valence/examples/player_list.rs, crates/valence/examples/resource_pack.rs, crates/valence/examples/terrain.rs, crates/valence/examples/text.rs, crates/valence/src/client.rs, crates/valence/src/client/event.rs, crates/valence/src/entity.rs, crates/valence/src/inventory.rs, crates/valence/src/lib.rs, crates/valence/src/player_list.rs, crates/valence/src/server.rs, crates/valence/src/unit_test/util.rs, crates/valence_anvil/Cargo.toml, crates/valence_anvil/examples/anvil_loading.rs
Fix #264
Bevy version is pinned to a recent commit on the main branch until 0.10 is released.
Run examples and tests. Behavior should be the same.
scheduling is a bit tricky so I may have made some subtle mistakes.
=> Update to Bevy 0.10

crates/valence/src/client.rs, crates/valence/src/inventory.rs, crates/valence/src/unit_test/util.rs
- update assert_packet_count with better fail message
- fix failing inventory unit test
Steps:
1. `cargo test -p valence --tests`
2. see that all inventory tests pass
=> fix inventory tests on `component-division`

crates/playground/src/extras.rs, crates/valence/examples/bench_players.rs, crates/valence/examples/building.rs, crates/valence/examples/chest.rs, crates/valence/src/server.rs
- fix duplicate Inventory component being placed on clients
- fix playground extras
- fix chest example so it builds
- fix building example
- fix bench players
Describe the changes you've made. Link to any issues that this PR fixes or addresses.
Explain the steps necessary to test your changes. If you used a playground, include the code in the details below.
Steps:
1.
<details>
```rust
```
</details>
=> misc fixes for `component-division`

crates/valence_protocol/src/packet/s2c/play/scoreboard_player_update.rs
Fix the contents of the `ScoreboardPlayerUpdateS2c` packet resolving #284.
Run the included playground code.
<details>
```rust
use valence::client::despawn_disconnected_clients;
use valence::client::event::default_event_handler;
use valence::protocol::packet::s2c::play::scoreboard_objective_update::{Mode, RenderType};
use valence::protocol::packet::s2c::play::scoreboard_player_update::Action;
use valence::protocol::packet::s2c::play::{
ScoreboardObjectiveUpdateS2c, ScoreboardPlayerUpdateS2c,
};
use valence::protocol::var_int::VarInt;
pub fn build_app(app: &mut App) {
app.add_plugin(ServerPlugin::new(()))
.add_system(default_event_handler.in_schedule(EventLoopSchedule))
.add_startup_system(setup)
.add_system(init_clients) …
```
=> Fix ScoreboardPlayerUpdate packet

crates/valence/src/inventory.rs
The client actually doesn't acknowledge the state id update when you modify the cursor item, so don't increment it so we stay in sync.
fixes #304
Explain the steps necessary to test your changes. If you used a playground, include the code in the details below.
Steps:
1. Run the playground from #304 (not included here for brevity)
2. open inventory (not chest)
3. pick up one of the stacks
4. see that you don't get resynced, and the apples stay in your cursor
=> don't increment state_id when the server modifies cursor item

crates/valence_block/build.rs, crates/valence_core/build/item.rs, crates/valence_core/build/packet_id.rs, crates/valence_core/build/sound.rs, crates/valence_core/build/translation_key.rs, crates/valence_entity/build.rs
This should _temporarily_ fix the heck issue described in #324 until https://github.com/withoutboats/heck/issues/42 is fixed downstream.
When it is fixed downstream, this commit should get reverted.
Fixes #324
=> Temp fix for heck with unicode enabled

crates/valence/examples/advancement.rs, crates/valence_advancement/src/lib.rs
Added a new reset flag, which resets all old advancements and don't show a toast for already completed advancements
Use example "advancements". Now it saves old progress of player
=> Advancement's reset flag

crates/valence_core/src/packet/decode.rs, crates/valence_network/src/connect.rs
=> Bungeecord join bug fix

crates/valence_client/src/lib.rs, crates/valence_core/src/lib.rs, crates/valence_core/src/protocol/packet.rs, crates/valence_core/src/protocol/var_int.rs, crates/valence_registry/Cargo.toml, crates/valence_registry/src/lib.rs, crates/valence_registry/src/tags.rs, extracted/tags.json, extractor/src/main/java/rs/valence/extractor/Main.java, extractor/src/main/java/rs/valence/extractor/extractors/Tags.java
- add Tags extractor
- add tags.json to extracted
- send `SynchronizeTagsS2c` packet on join
- fix encode
Adds a `TagsRegistry` resource that contains all the information needed to build and send `SynchronizeTagsS2c` on join.
closes #349
=> tag registry

Cargo.toml, crates/valence/examples/bench_players.rs, tools/stresser/Cargo.toml, tools/stresser/README.md, tools/stresser/src/stresser.rs
Closes #348. Updates the dependencies stressor uses, as well as bumping bench_players to allow 50k players (thanks to a new API change)
=> fix: update stressor, change max_players limit to 50k

.github/workflows/ci.yml, tools/packet_inspector/src/packet_io.rs
Describe the changes you've made. Link to any issues this PR fixes or addresses.
changed the clippy and fmt check to use nightly toolchain in ci
Fixes #381
=> Fix fmt in ci

.github/workflows/ci.yml
This reverts commit b1cb75f4cc8e1aec9504b0e19600da2b99e518be.
oops
=> Revert "Fix fmt in ci (#383)"

Cargo.toml, crates/valence_advancement/src/lib.rs, examples/anvil_loading.rs, examples/bench_players.rs, examples/biomes.rs, examples/block_entities.rs, examples/boss_bar.rs, examples/building.rs, examples/chest.rs, examples/combat.rs, examples/cow_sphere.rs, examples/death.rs, examples/game_of_life.rs, examples/parkour.rs, examples/particles.rs, examples/player_list.rs, examples/resource_pack.rs, examples/server_list_ping.rs, examples/terrain.rs, examples/text.rs, examples/world_border.rs, src/lib.rs, tools/playground/src/main.rs, tools/playground/src/playground.template.rs
Adds `bevy_log::LogPlugin` to `DefaultPlugins` behind an optional feature flag. It is no longer necessary to set up `tracing-subscriber` manually in the examples.
=> Add `bevy_log`

crates/valence_core/src/text.rs, crates/valence_network/src/connect.rs, crates/valence_network/src/legacy_ping.rs, crates/valence_network/src/lib.rs
Closes #282 
Any questions, insights, comments or criticism welcome.
=> Add server list legacy ping handler

examples/building.rs
Just a small PR fixing something I came across while reading around.
- Simplify the example
- Code de-duplication
=> Building example code de-duplication

crates/valence_world_border/src/lib.rs
Previously discussed in #410 and on discord.
=> Fix broken doctests from 61f2279

tools/packet_inspector/src/app/filter.rs
Fixes #447 
Make packet ids searchable
=> allow searching of packet ids in hex

Cargo.toml
This allows systems to run in parallel on different threads
=> enable the `multi-threaded` feature for `bevy_ecs`

src/tests.rs, src/tests/weather.rs
Added weather tests.
Fixes #434
=> Added weather tests

tools/packet_inspector/src/app.rs
Fixes #452 
guess i was looking at the wrong tab when creating my branch lol
=> 452 swap hex text view

crates/valence_entity/build.rs
related: #444
see: https://github.com/valence-rs/valence/pull/479#issuecomment-1684889433
=> derive `Deref` for components in `valence_entity`

examples/game_of_life.rs
Code in game of life example could be improved a bit
do that
=> Tweak game of life example

website/content/faq.md
Lots of new people pop up in the discord and ask this, so it would be nice to just point them to the FAQ instead.
=> web: add literally the most asked question to the FAQ

website/book/1-getting-started/setup.md, website/book/SUMMARY.md
- This article aims to guide new users starting new projects.
=> book: add a getting started/hello world guide

crates/valence_nbt/src/snbt.rs, crates/valence_text/src/tests.rs
This fixes the recent CI failures we've been getting.
=> hotfix clippy 1.72 lints

crates/valence_boss_bar/src/lib.rs, crates/valence_entity/src/lib.rs, crates/valence_protocol/src/biome_pos.rs, crates/valence_protocol/src/block_pos.rs, crates/valence_protocol/src/chunk_pos.rs, crates/valence_protocol/src/chunk_section_pos.rs, crates/valence_protocol/src/lib.rs, crates/valence_protocol/src/packets/play/chunk_delta_update_s2c.rs, crates/valence_server/src/client.rs, crates/valence_server/src/layer/chunk.rs, crates/valence_server/src/layer/chunk/loaded.rs, crates/valence_server/src/layer/entity.rs, crates/valence_server/src/lib.rs, examples/biomes.rs, examples/ctf.rs, examples/parkour.rs, src/tests/layer.rs
- Add `ChunkSectionPos` and `BiomePos` types.
- `From` conversions between position types.
- Packed block position and chunk section position types.
- Use `bitfield-struct` in more places.
=> Better position types

.github/workflows/ci.yml
- Give human-readable names to jobs in CI.
- Update ci.yml
=> Give human-readable names to CI jobs

crates/valence_protocol/src/packets/play/explosion_s2c.rs
fix explosion packet
fix some of the fields in accordance with https://wiki.vg/Protocol#Explosion.
=> fix explosion packet

crates/valence_anvil/src/lib.rs
- Fixes #530 
- Fixed some dumb code I wrote
=> Fix #530 - out of bounds memory writes in valence_anvil

crates/valence_entity/extracted/entities.json, crates/valence_generated/build/main.rs, crates/valence_generated/build/status_effects.rs, crates/valence_generated/extracted/effects.json, crates/valence_generated/src/lib.rs, crates/valence_protocol/src/lib.rs, extractor/copy_extractor_output.sh, extractor/src/main/java/rs/valence/extractor/Main.java, extractor/src/main/java/rs/valence/extractor/ValenceUtils.java, extractor/src/main/java/rs/valence/extractor/extractors/Effects.java, src/lib.rs
We need a way to acquire (and thus extract) all potion/status effects + their attributes
Also, #558 was getting really large.
I made an extractor.
Also, as per [the request](https://github.com/valence-rs/valence/pull/558#issuecomment-1760283675) of @dyc3, I split #558's extractor code into this pr.
=> Potions Extractor

crates/valence_entity/src/attributes.rs
I made a bad decision to use names instead of UUID, like how Minecraft does it. This means that implementing certain features won't behave like they do in Vanilla (e.g. potion effects like speed, and running. they use specific UUIDs)
- Use UUIDs
=> Refactor attribute modifiers to use UUID

crates/valence_entity/src/attributes.rs
I went a bit too fast yesterday and forgot a few `Uuid::new_v4()` at one location. @DasLixou pointed that out to me. Thx.
Fix it.
=> Fix attributes UUID stuff - I went a little too fast

.devcontainer/devcontainer.json
- So that anybody can open a codespace with rust and java on it
=> config gh codespace container

extractor/gradle.properties
Update the version of the extractor to 1.21.1
=> update extractor to 1.21.1

.github/workflows/website.yml
Try to fix the Publish Website workflow again
Update `deploy-pages` to `v4`
=> Fix Publish Website Workflow - Attempt 2
